name: ogindia-dev
channels:
dependencies:
- python
- "numpy>=1.14"
- "pandas>=0.23"
- "bokeh>=0.13"
- requests
- numba
- ipython
- setuptools
- mkl
- scipy>=0.18.1
- matplotlib
- dask>=0.20.0
- pytest
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- pip
- pip:
    - git+https://github.com/TPRU-India/taxcalc.git@master
